### ISSUE TITLE
Imagens não aparecem no site

### ISSUE THREAD

**Issue by youndaimesam** [youndaimesam/youndaimesam.github.io#1]
Os arquivos estão em subpastas no site, porém o site do github não as carrega, retorna erro 404.
Não foi erro de referencia, mas deveria ser testado.

**Comment by Davidepaalte** [comment]
Verifiquei que há um ficheiro CSS que também não está a ser carregado corretamente.
Parece-me que o github não suporta underscores no caminho do ficheiro. Experimenta remove-los do nome das pastas e das referências das mesmas no código.

**Comment by youndaimesam** [comment]
Funcionou, o site está completamento online
